### ISSUE TITLE
Error: the order does not exist

### ISSUE THREAD

**Issue by mikedaviesweb** [spicywebau/craft-reorder#10]
#### Description
On line 47 of ReorderController.php `if ($customer !== null && $currentUser->id === $customer->userId)` is returning `false` which results in the error "The order does not exist".  I believe this is because either `$currentUser->id` or `$customer->userId` is a String and the other a Number. 

#### Steps to reproduce
1. Install plugin
2. Add example code snippet to orders template
3. Submit reorder
4. Error flash message appears

#### Other information
- ReOrder version: 1.1.4
- Craft CMS version: 3.4.25
- Craft Commerce version: 3.2

**Comment by ttempleton** [comment]
Thanks for reporting this @mikedaviesweb, should now be fixed in ReOrder 1.1.5.
