### ISSUE TITLE
Error after reorder

### ISSUE THREAD

**Issue by denisPiskun** [spicywebau/craft-reorder#12]
We have this error message.
![image](https://github.com/spicywebau/craft-reorder/assets/126451543/37d86a50-681d-4134-81d9-dab7a2f6f34a)

need to remove line 110 line from \vendor\spicyweb\craft-reorder\src\controllers\ReorderController.php
to prevent return NULL, if there error

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 2.0.1.
