### ISSUE TITLE
Craft 5 compatibility

### ISSUE THREAD

**Issue by AndrewMac** [spicywebau/craft-reorder#13]
Hello there, Spicy Web

I can see that a lot of your plugins have been updated for Craft 5, but not yet this one. Can you advise what upgrade plans you may have, or is this product now retired?

Thanks, Andrew

**Comment by ttempleton** [comment]
Yes - this plugin will be coming to Craft 5. Hoping to update it next week.

**Comment by ttempleton** [comment]
We've just released ReOrder 3.0.0-beta.1 for Craft 5.
