### ISSUE TITLE
No items in cart causes error

### ISSUE THREAD

**Issue by andrewcgregory** [spicywebau/craft-reorder#3]
If there are no items in the cart, submitting a reorder button form causes an error for null line items. If there are items already in the cart then it works as it should.

`Argument 1 passed to craft\commerce\services\LineItems::resolveLineItem() must be of the type integer, null given, called in .../vendor/spicyweb/craft-reorder/src/Service.php on line 53`

**Comment by ttempleton** [comment]
Thanks for reporting this -- it has been fixed in v1.0.2.
