### ISSUE TITLE
Commerce 2.0.0-beta.12+ quantity not being set when re-ordering

### ISSUE THREAD

**Issue by engram-design** [spicywebau/craft-reorder#5]
We're just using `dev-develop` on commerce due to some other fixes, so nothing immediate to fix here, but putting it on your radar.

While line items are being populated correctly, their quantity is always set to 1.

```
<form method="POST">
    <input type="hidden" name="action" value="reorder/reorder">
    {{ csrfInput() }}
    {{ redirectInput('shop/checkout') }}
    <input type="hidden" name="order" value="{{ order.number }}">
    <input type="hidden" name="retainCart" value="0">
    <input type="hidden" name="allowPartial" value="1">

    <button class="btn btn-secondary" type="submit">Reorder</button>
</form>
```

Just a heads-up due to this change - https://github.com/craftcms/commerce/blob/9cc7dc3743489adf699805afc93362cfd28552af/CHANGELOG-v2.md#changed

**Comment by ttempleton** [comment]
Thanks!  This has now been updated in ReOrder v1.1.1.
