### ISSUE TITLE
Reordering specific items

### ISSUE THREAD

**Issue by matt-adigital** [spicywebau/craft-reorder#8]
Hi,

I've just installed this plugin and can't get the example code for reordering specific items to work. It seems that the commits for this functionality are present but haven't been added to a version release yet for this plugin.

Can you please release this feature or confirm why it has not been done so yet if issues are present? Thank you.

#### Other information
- ReOrder version: 1.1.2
- Craft CMS version: 3.1.29
- Craft Commerce version: 2.1.7

**Comment by pvldigital** [comment]
Ah yes, I totally forgot to make a release for it. It has now been done, v1.1.3.

**Comment by matt-adigital** [comment]
Perfect, thank you very much!
